// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxvlpggeszkmdccppmoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dmxwZ2dlc3prbWRjY3BwbW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzM3MzksImV4cCI6MjA2NTY0OTczOX0.YggxQC5QxroCgOvkqHGpFYQU-S1QljENn9E94wD20PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});